collections:
  authors:
    output: true

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: true
  startings: [head, body]


defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"